[processes.foo]
command = "while true; do echo foo; sleep 1; done"
shell = "/bin/sh"

[processes.bar]
command = "while true; do echo bar; sleep 2; done"
shell = "/bin/sh"

[processes.baz]
command = "for i in 1 2; do echo baz; sleep 3; done; exit 1"
shell = "/bin/sh"

[processes.qux]
command = "/usr/bin/sleep 20"
